# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'afficher_etudiant_numero.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import csv
from PyQt5.QtWidgets import QWidget, QTableWidget, QTableWidgetItem, QPushButton, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_affichage_etudiant_numero(object):
    def setupUi(self, affichage_etudiant_numero):
        affichage_etudiant_numero.setObjectName("affichage_etudiant_numero")
        affichage_etudiant_numero.resize(1300, 870)
        affichage_etudiant_numero.setStyleSheet("\n"
"")
        self.label = QtWidgets.QLabel(affichage_etudiant_numero)
        self.label.setGeometry(QtCore.QRect(0, 0, 1300, 870))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ressources/23.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(affichage_etudiant_numero)
        self.tableWidget.setGeometry(QtCore.QRect(20, 290, 1261, 341))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(136)
        self.label_2 = QtWidgets.QLabel(affichage_etudiant_numero)
        self.label_2.setGeometry(QtCore.QRect(160, 130, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(affichage_etudiant_numero)
        self.lineEdit.setGeometry(QtCore.QRect(640, 150, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(affichage_etudiant_numero)
        self.pushButton.setGeometry(QtCore.QRect(520, 700, 191, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.load_csv)

        self.retranslateUi(affichage_etudiant_numero)
        QtCore.QMetaObject.connectSlotsByName(affichage_etudiant_numero)
    def load_csv(self):
        numero=self.lineEdit.text()
        if not(numero.isdecimal() and len(numero)==8):
                QMessageBox.critical(None, "Erreur", "Le numéro d'inscription doit contenir 8 chiffres")
                return
        csv_file = "students.csv"
        with open(csv_file, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            header = next(reader)
            self.tableWidget.setColumnCount(len(header))
            self.tableWidget.setHorizontalHeaderLabels(header)
            self.tableWidget.setRowCount(0)
            found = False
            for row_data in reader:
                if row_data[0] == numero:
                    found = True
                    row = self.tableWidget.rowCount()
                    self.tableWidget.insertRow(row)
                    for column, item in enumerate(row_data):
                        self.tableWidget.setItem(row, column, QTableWidgetItem(item))
            if not found:
                QMessageBox.information(None, "Erreur", "Le numéro d'inscription {numero_inscription} n'existe pas dans notre base de données.")



    def retranslateUi(self, affichage_etudiant_numero):
        _translate = QtCore.QCoreApplication.translate
        affichage_etudiant_numero.setWindowTitle(_translate("affichage_etudiant_numero", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("affichage_etudiant_numero", "Numero inscription"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("affichage_etudiant_numero", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("affichage_etudiant_numero", "Prenom"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("affichage_etudiant_numero", "Date Naissance"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("affichage_etudiant_numero", "Adresse"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("affichage_etudiant_numero", "Mail"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("affichage_etudiant_numero", "Telephone"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("affichage_etudiant_numero", "Section"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("affichage_etudiant_numero", "Niveau Etude"))
        self.label_2.setText(_translate("affichage_etudiant_numero", "Entrer le numero d\'inscription"))
        self.pushButton.setText(_translate("affichage_etudiant_numero", "Afficher"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    affichage_etudiant_numero = QtWidgets.QWidget()
    ui = Ui_affichage_etudiant_numero()
    ui.setupUi(affichage_etudiant_numero)
    affichage_etudiant_numero.show()
    sys.exit(app.exec_())
