# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'affichage_etudiant_niveau.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import csv
from PyQt5.QtWidgets import QWidget, QTableWidget, QTableWidgetItem, QPushButton, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_affichage_etudiant_niveau(object):
    def setupUi(self, affichage_etudiant_niveau):
        affichage_etudiant_niveau.setObjectName("affichage_etudiant_niveau")
        affichage_etudiant_niveau.resize(1300, 870)
        self.label = QtWidgets.QLabel(affichage_etudiant_niveau)
        self.label.setGeometry(QtCore.QRect(0, 0, 1300, 870))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ressources/23.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(affichage_etudiant_niveau)
        self.tableWidget.setGeometry(QtCore.QRect(20, 220, 1261, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(136)
        self.label_2 = QtWidgets.QLabel(affichage_etudiant_niveau)
        self.label_2.setGeometry(QtCore.QRect(200, 110, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(affichage_etudiant_niveau)
        self.comboBox.setGeometry(QtCore.QRect(510, 115, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(3, "")
        self.pushButton = QtWidgets.QPushButton(affichage_etudiant_niveau)
        self.pushButton.setGeometry(QtCore.QRect(540, 750, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.load_csv)

        self.retranslateUi(affichage_etudiant_niveau)
        QtCore.QMetaObject.connectSlotsByName(affichage_etudiant_niveau)
    def load_csv(self):
        niveau=self.comboBox.currentText()
        
        csv_file = "students.csv"
        with open(csv_file, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            header = next(reader)
            self.tableWidget.setColumnCount(len(header))
            self.tableWidget.setHorizontalHeaderLabels(header)
            self.tableWidget.setRowCount(0)
            found = False
            for row_data in reader:
                if row_data[8] == niveau:
                    found = True
                    row = self.tableWidget.rowCount()
                    self.tableWidget.insertRow(row)
                    for column, item in enumerate(row_data):
                        self.tableWidget.setItem(row, column, QTableWidgetItem(item))
            if not found:
                QMessageBox.warning(None, "Erreur", f" aucun etudiant trouvé avec Le niveau d'étude {niveau}  dans notre base de données.")



    def retranslateUi(self, affichage_etudiant_niveau):
        _translate = QtCore.QCoreApplication.translate
        affichage_etudiant_niveau.setWindowTitle(_translate("affichage_etudiant_niveau", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("affichage_etudiant_niveau", "Numero inscription"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("affichage_etudiant_niveau", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("affichage_etudiant_niveau", "Prenom"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("affichage_etudiant_niveau", "Date Naissance"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("affichage_etudiant_niveau", "Adresse"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("affichage_etudiant_niveau", "Mail"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("affichage_etudiant_niveau", "Telephone"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("affichage_etudiant_niveau", "Section"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("affichage_etudiant_niveau", "Niveau Etude"))
        self.label_2.setText(_translate("affichage_etudiant_niveau", "Niveau d\'étude"))
        self.comboBox.setItemText(0, _translate("affichage_etudiant_niveau", "1 ére année"))
        self.comboBox.setItemText(1, _translate("affichage_etudiant_niveau", "2 éme année"))
        self.comboBox.setItemText(2, _translate("affichage_etudiant_niveau", "3 éme année"))
        self.pushButton.setText(_translate("affichage_etudiant_niveau", "Afficher"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    affichage_etudiant_niveau = QtWidgets.QWidget()
    ui = Ui_affichage_etudiant_niveau()
    ui.setupUi(affichage_etudiant_niveau)
    affichage_etudiant_niveau.show()
    sys.exit(app.exec_())
