# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'affichae_livre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QTableWidget, QTableWidgetItem, QPushButton, QVBoxLayout
import csv
from PyQt5.QtWidgets import QApplication, QMessageBox

class Ui_affichage_livre(object):
    def __init__(self):
        super().__init__()
    def setupUi(self, affichage_livre):
        affichage_livre.setObjectName("affichage_livre")
        affichage_livre.resize(1300, 870)
        affichage_livre.setStyleSheet("")
        self.label = QtWidgets.QLabel(affichage_livre)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1300, 870))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ressources/23.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(affichage_livre)
        self.tableWidget.setGeometry(QtCore.QRect(230, 180, 701, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(136)
        self.label_2 = QtWidgets.QLabel(affichage_livre)
        self.label_2.setGeometry(QtCore.QRect(380, 50, 641, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(affichage_livre)
        self.pushButton.setGeometry(QtCore.QRect(460, 750, 181, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.load_csv)
        self.label.raise_()
        self.tableWidget.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()

        self.retranslateUi(affichage_livre)
        QtCore.QMetaObject.connectSlotsByName(affichage_livre)
    def load_csv(self):
        csv_file = "livres.csv"
        # Chargement du fichier CSV
        with open(csv_file, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            # Ajout des en-têtes de colonne
            header = next(reader)
            self.tableWidget.setColumnCount(len(header))
            self.tableWidget.setHorizontalHeaderLabels(header)
            # Ajout des données dans le QTableWidget
            self.tableWidget.setRowCount(0)
            for row_data in reader:
                row = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row)
                for column, item in enumerate(row_data):
                    self.tableWidget.setItem(row, column, QTableWidgetItem(item))
            if self.tableWidget.rowCount() == 0:
                # Afficher une erreur dans un QMessageBox
                QMessageBox.warning(None, "Erreur", "Le fichier livre.csv est vide.")


    def retranslateUi(self, affichage_livre):
        _translate = QtCore.QCoreApplication.translate
        affichage_livre.setWindowTitle(_translate("affichage_livre", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("affichage_livre", "Reference"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("affichage_livre", "Titre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("affichage_livre", "Nom_auteru"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("affichage_livre", "Prénom_auteur"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("affichage_livre", "Année édition"))
        self.label_2.setText(_translate("affichage_livre", "Tableau des livres"))
        self.pushButton.setText(_translate("affichage_livre", "Afficher"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    affichage_livre = QtWidgets.QWidget()
    ui = Ui_affichage_livre()
    ui.setupUi(affichage_livre)
    affichage_livre.show()
    sys.exit(app.exec_())
