# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'affichage_emprunt_date_emprunt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import csv
from PyQt5.QtWidgets import QWidget, QTableWidget, QTableWidgetItem, QPushButton, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_affichage_emprunt_date_emprunt(object):
    def setupUi(self, affichage_emprunt_date_emprunt):
        affichage_emprunt_date_emprunt.setObjectName("affichage_emprunt_date_emprunt")
        affichage_emprunt_date_emprunt.resize(1300, 870)
        self.label = QtWidgets.QLabel(affichage_emprunt_date_emprunt)
        self.label.setGeometry(QtCore.QRect(0, 0, 1300, 870))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ressources/23.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(affichage_emprunt_date_emprunt)
        self.tableWidget.setGeometry(QtCore.QRect(240, 240, 751, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(188)
        self.label_2 = QtWidgets.QLabel(affichage_emprunt_date_emprunt)
        self.label_2.setGeometry(QtCore.QRect(240, 130, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(affichage_emprunt_date_emprunt)
        self.dateEdit.setGeometry(QtCore.QRect(640, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(affichage_emprunt_date_emprunt)
        self.pushButton.setGeometry(QtCore.QRect(560, 750, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.load_csv)

        self.retranslateUi(affichage_emprunt_date_emprunt)
        QtCore.QMetaObject.connectSlotsByName(affichage_emprunt_date_emprunt)
    def load_csv(self):
        date=self.dateEdit.text()
        
        csv_file = "emprunt.csv"
        with open(csv_file, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            header = next(reader)
            self.tableWidget.setColumnCount(len(header))
            self.tableWidget.setHorizontalHeaderLabels(header)
            self.tableWidget.setRowCount(0)
            found = False
            for row_data in reader:
                if row_data[3] == date:
                    found = True
                    row = self.tableWidget.rowCount()
                    self.tableWidget.insertRow(row)
                    for column, item in enumerate(row_data):
                        self.tableWidget.setItem(row, column, QTableWidgetItem(item))
            if not found:
                QMessageBox.information(None, "Erreur", f"aucun livre publié a la date {date}.")


    def retranslateUi(self, affichage_emprunt_date_emprunt):
        _translate = QtCore.QCoreApplication.translate
        affichage_emprunt_date_emprunt.setWindowTitle(_translate("affichage_emprunt_date_emprunt", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("affichage_emprunt_date_emprunt", "Numéro_inscription"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("affichage_emprunt_date_emprunt", "Référence_livre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("affichage_emprunt_date_emprunt", "Date_emprunt"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("affichage_emprunt_date_emprunt", "Date_retour"))
        self.label_2.setText(_translate("affichage_emprunt_date_emprunt", "Donner la date d'emprunt"))
        self.pushButton.setText(_translate("affichage_emprunt_date_emprunt", "Afficher"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    affichage_emprunt_date_emprunt = QtWidgets.QWidget()
    ui = Ui_affichage_emprunt_date_emprunt()
    ui.setupUi(affichage_emprunt_date_emprunt)
    affichage_emprunt_date_emprunt.show()
    sys.exit(app.exec_())
