# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'affichage_etudaint_section.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import csv
from PyQt5.QtWidgets import QWidget, QTableWidget, QTableWidgetItem, QPushButton, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox



class Ui_affichage_etudaint_section(object):
    def setupUi(self, affichage_etudaint_section):
        affichage_etudaint_section.setObjectName("affichage_etudaint_section")
        affichage_etudaint_section.resize(1300, 870)
        self.label = QtWidgets.QLabel(affichage_etudaint_section)
        self.label.setGeometry(QtCore.QRect(0, 0, 1300, 870))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ressources/23.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(affichage_etudaint_section)
        self.tableWidget.setGeometry(QtCore.QRect(20, 220, 1261, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(136)
        self.label_2 = QtWidgets.QLabel(affichage_etudaint_section)
        self.label_2.setGeometry(QtCore.QRect(260, 110, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(affichage_etudaint_section)
        self.comboBox.setGeometry(QtCore.QRect(450, 110, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(affichage_etudaint_section)
        self.pushButton.setGeometry(QtCore.QRect(550, 757, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.load_csv)

        self.retranslateUi(affichage_etudaint_section)
        QtCore.QMetaObject.connectSlotsByName(affichage_etudaint_section)
    def load_csv(self):
        section=self.comboBox.currentText()
        
        csv_file = "students.csv"
        with open(csv_file, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            header = next(reader)
            self.tableWidget.setColumnCount(len(header))
            self.tableWidget.setHorizontalHeaderLabels(header)
            self.tableWidget.setRowCount(0)
            found = False
            for row_data in reader:
                if row_data[7] == section:
                    found = True
                    row = self.tableWidget.rowCount()
                    self.tableWidget.insertRow(row)
                    for column, item in enumerate(row_data):
                        self.tableWidget.setItem(row, column, QTableWidgetItem(item))
            if not found:
                QMessageBox.information(None, "Erreur", f"aucun etudiant pour La section {section}  dans notre base de données.")



    def retranslateUi(self, affichage_etudaint_section):
        _translate = QtCore.QCoreApplication.translate
        affichage_etudaint_section.setWindowTitle(_translate("affichage_etudaint_section", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("affichage_etudaint_section", "Numero inscription"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("affichage_etudaint_section", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("affichage_etudaint_section", "Prenom"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("affichage_etudaint_section", "Date Naissance"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("affichage_etudaint_section", "Adresse"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("affichage_etudaint_section", "Mail"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("affichage_etudaint_section", "Telephone"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("affichage_etudaint_section", "Section"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("affichage_etudaint_section", "Niveau Etude"))
        self.label_2.setText(_translate("affichage_etudaint_section", "Section"))
        self.comboBox.setItemText(0, _translate("Form", "Cycle Préparatoire intégrée"))
        self.comboBox.setItemText(1, _translate("affichage_etudaint_section", "License Info"))
        self.comboBox.setItemText(2, _translate("affichage_etudaint_section", "License Tic"))
        self.comboBox.setItemText(3, _translate("affichage_etudaint_section", "License électronique"))
        self.comboBox.setItemText(4, _translate("affichage_etudaint_section", "Ingénieur électronique"))
        self.comboBox.setItemText(5, _translate("affichage_etudaint_section", "Ingénieur Informatique"))
        self.pushButton.setText(_translate("affichage_etudaint_section", "Afficher"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    affichage_etudaint_section = QtWidgets.QWidget()
    ui = Ui_affichage_etudaint_section()
    ui.setupUi(affichage_etudaint_section)
    affichage_etudaint_section.show()
    sys.exit(app.exec_())
