# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'affichage_livre_annee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import csv
from PyQt5.QtWidgets import QWidget, QTableWidget, QTableWidgetItem, QPushButton, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_affichage_livre_annee(object):
    def setupUi(self, affichage_livre_annee):
        affichage_livre_annee.setObjectName("affichage_livre_annee")
        affichage_livre_annee.resize(1300, 870)
        affichage_livre_annee.setStyleSheet("")
        self.label = QtWidgets.QLabel(affichage_livre_annee)
        self.label.setGeometry(QtCore.QRect(0, 0, 1300, 870))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ressources/23.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(affichage_livre_annee)
        self.tableWidget.setGeometry(QtCore.QRect(240, 210, 701, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(136)
        self.label_2 = QtWidgets.QLabel(affichage_livre_annee)
        self.label_2.setGeometry(QtCore.QRect(240, 130, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(affichage_livre_annee)
        self.lineEdit.setGeometry(QtCore.QRect(550, 121, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(affichage_livre_annee)
        self.pushButton.setGeometry(QtCore.QRect(480, 770, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.load_csv)

        self.retranslateUi(affichage_livre_annee)
        QtCore.QMetaObject.connectSlotsByName(affichage_livre_annee)
    def load_csv(self):
        annee=self.lineEdit.text()
        if not(annee.isdigit() and len(annee)==4 and  int(annee)<=2023 ):
                QMessageBox.critical(None, "Erreur", "L'année doit etre 4 chiffres et inférieure a 2023")
                return
        csv_file = "livres.csv"
        with open(csv_file, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            header = next(reader)
            self.tableWidget.setColumnCount(len(header))
            self.tableWidget.setHorizontalHeaderLabels(header)
            self.tableWidget.setRowCount(0)
            found = False
            for row_data in reader:
                if row_data[4] == annee:
                    found = True
                    row = self.tableWidget.rowCount()
                    self.tableWidget.insertRow(row)
                    for column, item in enumerate(row_data):
                        self.tableWidget.setItem(row, column, QTableWidgetItem(item))
            if not found:
                 QMessageBox.information(None, "Aucun livre trouvé", f"Aucun livre publié cette année {annee}-là n'a été trouvé.")
    def retranslateUi(self, affichage_livre_annee):
        _translate = QtCore.QCoreApplication.translate
        affichage_livre_annee.setWindowTitle(_translate("affichage_livre_annee", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("affichage_livre_annee", "Reference"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("affichage_livre_annee", "Titre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("affichage_livre_annee", "Nom_auteru"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("affichage_livre_annee", "Prénom_auteur"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("affichage_livre_annee", "Année édition"))
        self.label_2.setText(_translate("affichage_livre_annee", "Année d\'édition"))
        self.pushButton.setText(_translate("affichage_livre_annee", "Afficher"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    affichage_livre_annee = QtWidgets.QWidget()
    ui = Ui_affichage_livre_annee()
    ui.setupUi(affichage_livre_annee)
    affichage_livre_annee.show()
    sys.exit(app.exec_())
