# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os.path
import ressources
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QApplication, QMessageBox
import csv


class Ui_Form(object):
    def __init__(self):
        self.dic = {}
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1300, 870)
        Form.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(18, 178, 255, 254), stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(:/ressources/23.jpg);\n"
"background-color: rgb(54, 54, 54);")
        self.b = QtWidgets.QPushButton(Form)
        self.b.setGeometry(QtCore.QRect(380, 780, 411, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(16)
        self.b.setFont(font)
        self.b.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.b.setObjectName("b")
        self.b.clicked.connect(self.ajout)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(250, 80, 241, 701))
        self.widget.setStyleSheet("background:transparent;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(420, 10, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_10.setObjectName("label_10")
        self.l1 = QtWidgets.QLineEdit(Form)
        self.l1.setGeometry(QtCore.QRect(590, 100, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLineEdit(Form)
        self.l2.setGeometry(QtCore.QRect(590, 170, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2.setFont(font)
        self.l2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLineEdit(Form)
        self.l3.setGeometry(QtCore.QRect(590, 240, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l3.setFont(font)
        self.l3.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l3.setObjectName("l3")
        self.l5 = QtWidgets.QLineEdit(Form)
        self.l5.setGeometry(QtCore.QRect(590, 400, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l5.setFont(font)
        self.l5.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l5.setObjectName("l5")
        self.l4 = QtWidgets.QDateEdit(Form)
        self.l4.setGeometry(QtCore.QRect(590, 320, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l4.setFont(font)
        self.l4.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l4.setObjectName("l4")
        self.l6 = QtWidgets.QLineEdit(Form)
        self.l6.setGeometry(QtCore.QRect(590, 470, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l6.setFont(font)
        self.l6.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l6.setObjectName("l6")
        self.l7 = QtWidgets.QLineEdit(Form)
        self.l7.setGeometry(QtCore.QRect(590, 540, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l7.setFont(font)
        self.l7.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l7.setObjectName("l7")
        self.l8 = QtWidgets.QComboBox(Form)
        self.l8.setGeometry(QtCore.QRect(590, 620, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l8.setFont(font)
        self.l8.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l8.setObjectName("l8")
        self.l8.addItem("")
        self.l8.addItem("")
        self.l8.addItem("")
        self.l8.addItem("")
        self.l8.addItem("")
        self.l8.addItem("")
        self.l9 = QtWidgets.QComboBox(Form)
        self.l9.setGeometry(QtCore.QRect(590, 710, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l9.setFont(font)
        self.l9.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l9.setObjectName("l9")
        self.l9.addItem("")
        self.l9.addItem("")
        self.l9.addItem("")
        self.l9.addItem("")
        self.l9.setItemText(3, "")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def ajout(self):
        while True:
            numero_inscription=self.l1.text()
            if not(numero_inscription.isdecimal() and len(numero_inscription)==8):
                QMessageBox.critical(None, "Erreur", "Le numéro d'inscription doit contenir 8 chiffres")
                break
            nom=self.l2.text()
            if not(nom.isalpha() and len(nom)<=30):
                QMessageBox.critical(None, "Erreur", "Le nom doit etre alphabetique et contient au maximum 30 caracteres")
                break
            prenom=self.l3.text()
            if not(prenom.isalpha() and len(prenom)<=30):
                QMessageBox.critical(None, "Erreur", "Le prenom doit etre alphabetique et contient au maximum 30 caracteres")
                break
            date_naissance=self.l4.text()
            adresse=self.l5.text()
            if not(adresse.isalpha() and len(adresse)<=20):
                QMessageBox.critical(None, "Erreur", "L'adresse doit etre alphabetique et contient au maximum 20 caracteres")
                break
            mail=self.l6.text()
            telephone=self.l7.text()
            if(telephone.isdecimal() and len(telephone)!=8 and telephone[0] in ['2','4','5','9']):
                QMessageBox.critical(None, "Erreur", "Le telephone doit contenir 8 chiffres ")
                break
            section=self.l8.currentText()
            Niveau_etude=self.l9.currentText()
            self.dic[numero_inscription]=[nom,prenom,date_naissance,adresse,mail,telephone,section,Niveau_etude ]
            if not os.path.exists('students.csv'):
                with open('students.csv', mode='w', newline='') as file:
                    fieldnames = ['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse', 'mail', 'telephone', 'section', 'niveau_etude']
                    writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                    writer.writeheader()
            with open('students.csv', mode='r', newline='') as file:
                reader = csv.DictReader(file, delimiter=',', quotechar='"')
                for row in reader:
                    if row['numero_inscription'] == numero_inscription:
                        QMessageBox.information(None, "information", "Le numéro d'inscription existe déjà dans le fichier")
                        return
                else:
                    with open('students.csv', mode='a', newline='') as file:
                        fieldnames = ['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse', 'mail', 'telephone', 'section', 'niveau_etude']
                        writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                        writer.writerow({
                             'numero_inscription': numero_inscription,
                             'nom': nom,
                             'prenom': prenom,
                             'date_naissance': date_naissance,
                             'adresse': adresse,
                             'mail': mail,
                             'telephone': telephone,
                             'section': section,
                             'niveau_etude': Niveau_etude, })
                        QMessageBox.information(None,"information",f"l'étudiant ayant le numéro inscription {numero_inscription} a été ajouté avec succés.",)
                        break
                return self.dic
                
            

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b.setText(_translate("Form", "ajouter"))
        self.label.setText(_translate("Form", "Numéro inscription "))
        self.label_2.setText(_translate("Form", "Nom"))
        self.label_3.setText(_translate("Form", "Prénom"))
        self.label_5.setText(_translate("Form", "Date de naissance"))
        self.label_4.setText(_translate("Form", "Adresse"))
        self.label_8.setText(_translate("Form", "Mail"))
        self.label_7.setText(_translate("Form", "Téléphone"))
        self.label_6.setText(_translate("Form", "Section"))
        self.label_9.setText(_translate("Form", "Niveau étude"))
        self.label_10.setText(_translate("Form", "Ajout des étudiants"))
        self.l8.setItemText(0, _translate("Form", "Cycle Préparatoire intégrée"))
        self.l8.setItemText(1, _translate("Form", "License Info"))
        self.l8.setItemText(2, _translate("Form", "License Tic"))
        self.l8.setItemText(3, _translate("Form", "License électronique"))
        self.l8.setItemText(4, _translate("Form", "Ingénieur électronique"))
        self.l8.setItemText(5, _translate("Form", "Ingéniuer Informatique"))
        self.l9.setItemText(0, _translate("Form", "1 ére année"))
        self.l9.setItemText(1, _translate("Form", "2 éme année"))
        self.l9.setItemText(2, _translate("Form", "3 éme année"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
