# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout_emprunt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os.path
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources

class Ui_ajouteremprunt(object):
    def __init__(self):
        self.dicemprunt = {}
    def setupUi(self, ajouteremprunt):
        ajouteremprunt.setObjectName("ajouteremprunt")
        ajouteremprunt.resize(1300, 800)
        ajouteremprunt.setMaximumSize(QtCore.QSize(1300, 870))
        ajouteremprunt.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-image: url(:/ressources/23.jpg);\n"
"background-color: rgb(54, 54, 54);")
        self.ajoutemprunt = QtWidgets.QPushButton(ajouteremprunt)
        self.ajoutemprunt.setGeometry(QtCore.QRect(340, 600, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.ajoutemprunt.setFont(font)
        self.ajoutemprunt.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.ajoutemprunt.setObjectName("ajoutemprunt")
        self.ajoutemprunt.clicked.connect(self.ajout_emprunt)
        self.label_5 = QtWidgets.QLabel(ajouteremprunt)
        self.label_5.setGeometry(QtCore.QRect(290, 70, 401, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(ajouteremprunt)
        self.label.setGeometry(QtCore.QRect(210, 280, 230, 33))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(ajouteremprunt)
        self.label_4.setGeometry(QtCore.QRect(210, 370, 136, 33))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"b\n"
"border-radius:10px\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(ajouteremprunt)
        self.label_2.setGeometry(QtCore.QRect(210, 200, 179, 33))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ajouteremprunt)
        self.label_3.setGeometry(QtCore.QRect(200, 460, 181, 33))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_3.setObjectName("label_3")
        self.lemp1 = QtWidgets.QLineEdit(ajouteremprunt)
        self.lemp1.setGeometry(QtCore.QRect(530, 200, 178, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lemp1.setFont(font)
        self.lemp1.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lemp1.setObjectName("lemp1")
        self.lemp2 = QtWidgets.QLineEdit(ajouteremprunt)
        self.lemp2.setGeometry(QtCore.QRect(530, 290, 178, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lemp2.setFont(font)
        self.lemp2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lemp2.setObjectName("lemp2")
        self.dateEdit_2 = QtWidgets.QDateEdit(ajouteremprunt)
        self.dateEdit_2.setGeometry(QtCore.QRect(530, 370, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(ajouteremprunt)
        self.dateEdit.setGeometry(QtCore.QRect(530, 460, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(ajouteremprunt)
        QtCore.QMetaObject.connectSlotsByName(ajouteremprunt)
    def ajout_emprunt(self):
        while True:
            numero_inscription=self.lemp2.text()
            if not(numero_inscription.isdecimal() and len(numero_inscription)==8):
                QMessageBox.critical(None, "Erreur", "Le numéro d'inscription doit contenir 8 chiffres")
                break
            reference_livre=self.lemp1.text()
            date_emprunt=self.dateEdit_2.text()
            date_retour=self.dateEdit.text()
            self.dicemprunt[numero_inscription] = [reference_livre, date_emprunt, date_retour]
            if not os.path.exists('emprunt.csv'):
                with open('emprunt.csv', mode='w', newline='') as file:
                    fieldnames = ['numero_inscription', 'reference_livre', 'date_emprunt', 'date_retour']
                    writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                    writer.writeheader()
            with open('emprunt.csv', mode='r', newline='') as file:
                reader = csv.DictReader(file, delimiter=',', quotechar='"')
                for row in reader:
                    if (row['numero_inscription'] == numero_inscription and row['reference_livre']==reference_livre):
                        QMessageBox.critical(None, "Erreur", "cet emprunt existe déjà dans le fichier")
                        return
                else:
                    with open('emprunt.csv', mode='a', newline='') as file:
                        fieldnames = ['numero_inscription', 'reference_livre', 'date_emprunt', 'date_retour',]
                        writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                        writer.writerow({
                            'numero_inscription': numero_inscription,
                            'reference_livre': reference_livre,
                            'date_emprunt': date_emprunt,
                            'date_retour': date_retour,  })
                        QMessageBox.information(None,"information","Les informations ont été enregistrées dans le fichier emprunt.csv.",)
                        break
                return self.dicemprunt
                                                

    def retranslateUi(self, ajouteremprunt):
        _translate = QtCore.QCoreApplication.translate
        ajouteremprunt.setWindowTitle(_translate("ajouteremprunt", "Form"))
        self.ajoutemprunt.setText(_translate("ajouteremprunt", "ajouter"))
        self.label_5.setText(_translate("ajouteremprunt", "Ajout des emprunts"))
        self.label.setText(_translate("ajouteremprunt", "numéro inscription"))
        self.label_4.setText(_translate("ajouteremprunt", "date retour"))
        self.label_2.setText(_translate("ajouteremprunt", "référence livre"))
        self.label_3.setText(_translate("ajouteremprunt", "date d\'emprunt"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ajouteremprunt = QtWidgets.QWidget()
    ui = Ui_ajouteremprunt()
    ui.setupUi(ajouteremprunt)
    ajouteremprunt.show()
    sys.exit(app.exec_())
