# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifier_telephone.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources

class Ui_modifier_telephone(object):
    def setupUi(self, modifier_telephone):
        modifier_telephone.setObjectName("modifier_telephone")
        modifier_telephone.resize(1024, 840)
        modifier_telephone.setMaximumSize(QtCore.QSize(1024, 840))
        modifier_telephone.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"background-image: url(:/ressources/23.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(modifier_telephone)
        self.label.setGeometry(QtCore.QRect(120, 270, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(modifier_telephone)
        self.lineEdit.setGeometry(QtCore.QRect(560, 270, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit.setObjectName("lineEdit")
        self.modiftel = QtWidgets.QPushButton(modifier_telephone)
        self.modiftel.setGeometry(QtCore.QRect(350, 590, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.modiftel.setFont(font)
        self.modiftel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(54, 54, 54);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.modiftel.setObjectName("modiftel")
        self.modiftel.clicked.connect(self.modifier_telephone)
        self.label_2 = QtWidgets.QLabel(modifier_telephone)
        self.label_2.setGeometry(QtCore.QRect(120, 410, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(modifier_telephone)
        self.lineEdit_2.setGeometry(QtCore.QRect(570, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(modifier_telephone)
        self.label_3.setGeometry(QtCore.QRect(340, 110, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(modifier_telephone)
        QtCore.QMetaObject.connectSlotsByName(modifier_telephone)
    def modifier_telephone(self):
        ancien_telephone = self.lineEdit.text()
        nouveau_telephone = self.lineEdit_2.text()
        if not(ancien_telephone.isdecimal() and len(ancien_telephone) == 8 and nouveau_telephone.isdecimal() and len(nouveau_telephone) == 8):
            QMessageBox.critical(None, "Erreur", "Les numéros de téléphone doivent contenir 8 chiffres")
            return
        with open('students.csv', mode='r') as file:
            # Read the contents of the file
            reader = csv.DictReader(file)
            rows = [row for row in reader]
        found_student = False
        for row in rows:
            if row['telephone'] == ancien_telephone:
                row['telephone'] = nouveau_telephone
                found_student = True
                break
        if not found_student:
            QMessageBox.information(None, "Erreur", f"Aucun étudiant avec ce numéro de téléphone {ancien_telephone} dans notre base de données")
            return
        with open('students.csv', mode='w', newline='') as file:
            fieldnames = ['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse', 'mail', 'telephone', 'section', 'niveau_etude']
            writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            writer.writeheader()
            writer.writerows(rows)
        
        QMessageBox.information(None, "Information", f"Le numéro de téléphone {ancien_telephone} a été modifié par {nouveau_telephone}")

    def retranslateUi(self, modifier_telephone):
        _translate = QtCore.QCoreApplication.translate
        modifier_telephone.setWindowTitle(_translate("modifier_telephone", "Form"))
        self.label.setText(_translate("modifier_telephone", "Entrer l ancien téléphone"))
        self.modiftel.setText(_translate("modifier_telephone", "Modifier"))
        self.label_2.setText(_translate("modifier_telephone", "Entrer le niveau téléphone"))
        self.label_3.setText(_translate("modifier_telephone", "Modification du téléphone"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modifier_telephone = QtWidgets.QWidget()
    ui = Ui_modifier_telephone()
    ui.setupUi(modifier_telephone)
    modifier_telephone.show()
    sys.exit(app.exec_())
