# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifier_mail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources

class Ui_modifier_mail(object):
    def setupUi(self, modifier_mail):
        modifier_mail.setObjectName("modifier_mail")
        modifier_mail.resize(1024, 840)
        modifier_mail.setMaximumSize(QtCore.QSize(1024, 840))
        modifier_mail.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(18, 178, 255, 254), stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(:/ressources/23.jpg);\n"
"background-color: rgb(54, 54, 54);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(modifier_mail)
        self.label.setGeometry(QtCore.QRect(100, 270, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.modifmail = QtWidgets.QPushButton(modifier_mail)
        self.modifmail.setGeometry(QtCore.QRect(380, 560, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.modifmail.setFont(font)
        self.modifmail.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.modifmail.setObjectName("modifmail")
        self.modifmail.clicked.connect(self.modifier_mail)
        self.lmodifmail = QtWidgets.QLineEdit(modifier_mail)
        self.lmodifmail.setGeometry(QtCore.QRect(460, 280, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lmodifmail.setFont(font)
        self.lmodifmail.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lmodifmail.setObjectName("lmodifmail")
        self.label_2 = QtWidgets.QLabel(modifier_mail)
        self.label_2.setGeometry(QtCore.QRect(100, 410, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(modifier_mail)
        self.lineEdit.setGeometry(QtCore.QRect(460, 420, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(modifier_mail)
        self.label_3.setGeometry(QtCore.QRect(330, 120, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(modifier_mail)
        QtCore.QMetaObject.connectSlotsByName(modifier_mail)
    def modifier_mail(self):
        ancien_mail = self.lmodifmail.text()
        nouveau_mail = self.lineEdit.text()
        with open('students.csv', mode='r') as file:
            # Read the contents of the file
            reader = csv.DictReader(file)
            rows = [row for row in reader]
        found_student = False
        for row in rows:
            if row['mail'] == ancien_mail:
                row['mail'] = nouveau_mail
                found_student = True
                break
            
        if not found_student:
            QMessageBox.information(None, "Erreur", f"Aucun étudiant avec ce Mail {ancien_mail}  dans notre base de données")
            return
        with open('students.csv', mode='w', newline='') as file:
            fieldnames = ['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse', 'mail', 'telephone', 'section', 'niveau_etude']
            writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            writer.writeheader()
            writer.writerows(rows)
        QMessageBox.information(None, "Information", f"Le Mail {ancien_mail} a été modifié par {nouveau_mail}")
        
        

    def retranslateUi(self, modifier_mail):
        _translate = QtCore.QCoreApplication.translate
        modifier_mail.setWindowTitle(_translate("Modifier_Mail", "Form"))
        self.label.setText(_translate("modifier_Mail", "Entrer l\'ancien Mail"))
        self.modifmail.setText(_translate("modifier_Mail", "modifier"))
        self.label_2.setText(_translate("modifier_Mail", "Entrer le nouveau Mail"))
        self.label_3.setText(_translate("modifier_Mail", "Modification du Mail"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modifier_mail = QtWidgets.QWidget()
    ui = Ui_modifier_mail()
    ui.setupUi(modifier_mail)
    modifier_mail.show()
    sys.exit(app.exec_())
