# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppression_livre_auteur.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_suppression_livre_auteur(object):
    def setupUi(self, suppression_livre_auteur):
        suppression_livre_auteur.setObjectName("suppression_livre_auteur")
        suppression_livre_auteur.resize(1024, 840)
        suppression_livre_auteur.setMaximumSize(QtCore.QSize(1024, 840))
        suppression_livre_auteur.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"background-image: url(:/ressources/23.jpg);")
        self.label = QtWidgets.QLabel(suppression_livre_auteur)
        self.label.setGeometry(QtCore.QRect(160, 340, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(suppression_livre_auteur)
        self.lineEdit.setGeometry(QtCore.QRect(570, 350, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.supplivreauteur = QtWidgets.QPushButton(suppression_livre_auteur)
        self.supplivreauteur.setGeometry(QtCore.QRect(350, 540, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.supplivreauteur.setFont(font)
        self.supplivreauteur.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.supplivreauteur.setObjectName("supplivreauteur")
        self.supplivreauteur.clicked.connect(self.supprimer_livre_auteur)
        self.label_2 = QtWidgets.QLabel(suppression_livre_auteur)
        self.label_2.setGeometry(QtCore.QRect(240, 140, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(suppression_livre_auteur)
        QtCore.QMetaObject.connectSlotsByName(suppression_livre_auteur)
    def supprimer_livre_auteur(self):
        nom_auteur = self.lineEdit.text()
        if not(nom_auteur.isalpha() and len(nom_auteur)<=20):
            QMessageBox.critical(None, "Erreur", "Le nom de l'auteur doit etre alphabetique et au maximum 20 caractéres")
            return
        with open('livres.csv', 'r') as f:
            reader = csv.DictReader(f)
            livres = list(reader)
        # Chercher les livres de l'année spécifiée
        livres_auteur = [livre for livre in livres if livre['nom_auteur'] == nom_auteur]
        if not livres_auteur:
            QMessageBox.information(None, "Aucun livre trouvé", f"le nom {nom_auteur} n'existe pas dans notre base de données.")
            return
        livres_restants = [livre for livre in livres if livre not in livres_auteur]
        with open('livres.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['reference', 'titre', 'nom_auteur', 'prenom_auteur', 'annee_edition'])
            writer.writeheader()
            writer.writerows(livres_restants)
        QMessageBox.information(None, "Livres supprimés", f"Les livres publiés avec l auteur: {nom_auteur} ont été supprimés avec succès.")
           
        
            
        
        

    def retranslateUi(self, suppression_livre_auteur):
        _translate = QtCore.QCoreApplication.translate
        suppression_livre_auteur.setWindowTitle(_translate("suppression_livre_auteur", "Form"))
        self.label.setText(_translate("suppression_livre_auteur", "entrer le nom_auteur"))
        self.supplivreauteur.setText(_translate("suppression_livre_auteur", "supprimer"))
        self.label_2.setText(_translate("suppression_livre_auteur", "Suppression livre par auteur"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppression_livre_auteur = QtWidgets.QWidget()
    ui = Ui_suppression_livre_auteur()
    ui.setupUi(suppression_livre_auteur)
    suppression_livre_auteur.show()
    sys.exit(app.exec_())
