# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppression_emprunt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_suppression_emprunt(object):
    def setupUi(self, suppression_emprunt):
        suppression_emprunt.setObjectName("suppression_emprunt")
        suppression_emprunt.resize(1300, 870)
        suppression_emprunt.setStyleSheet("background-image: url(:/ressources/23.jpg);")
        self.label = QtWidgets.QLabel(suppression_emprunt)
        self.label.setGeometry(QtCore.QRect(250, 270, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(suppression_emprunt)
        self.label_2.setGeometry(QtCore.QRect(250, 430, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(suppression_emprunt)
        self.lineEdit.setGeometry(QtCore.QRect(760, 280, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(suppression_emprunt)
        self.lineEdit_2.setGeometry(QtCore.QRect(760, 440, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(suppression_emprunt)
        self.label_3.setGeometry(QtCore.QRect(440, 70, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(suppression_emprunt)
        self.pushButton.setGeometry(QtCore.QRect(560, 640, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.supprimer)

        self.retranslateUi(suppression_emprunt)
        QtCore.QMetaObject.connectSlotsByName(suppression_emprunt)
    def supprimer(self):
        numero_inscription=self.lineEdit.text()
        if not(numero_inscription.isdecimal() and len(numero_inscription)==8):
            QMessageBox.critical(None, "Erreur", "Le numéro d'inscription doit contenir 8 chiffres")
            return
        reference=self.lineEdit_2.text()
        with open('emprunt.csv', 'r') as f:
            reader = csv.DictReader(f)
            students = list(reader)
        etudiant_numero = [students for students in students if students['numero_inscription'] == numero_inscription and students['reference_livre']==reference]
        if not etudiant_numero:
            QMessageBox.information(None, "Aucun emprunt trouvé", f"Aucun emprunt trouvé pour le numero_inscription {numero_inscription} du reference{reference}.")
            return
        etudiant_restants = [students for students in students if students not in etudiant_numero]
        with open('emprunt.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['numero_inscription', 'reference_livre', 'date_emprunt', 'date_retour'])
            writer.writeheader()
            writer.writerows(etudiant_restants)
        QMessageBox.information(None, "emprunt supprimé", f"L emprunt de numero inscription{numero_inscription} de livre de reference {reference} est supprimé avec succès.")
             
        

    def retranslateUi(self, suppression_emprunt):
        _translate = QtCore.QCoreApplication.translate
        suppression_emprunt.setWindowTitle(_translate("suppression_emprunt", "Form"))
        self.label.setText(_translate("suppression_emprunt", "Entrer le Numéro d\'inscription"))
        self.label_2.setText(_translate("suppression_emprunt", "Entrer le Référence_livre"))
        self.label_3.setText(_translate("suppression_emprunt", "Suppression Emprunt"))
        self.pushButton.setText(_translate("suppression_emprunt", "Supprimer"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppression_emprunt = QtWidgets.QWidget()
    ui = Ui_suppression_emprunt()
    ui.setupUi(suppression_emprunt)
    suppression_emprunt.show()
    sys.exit(app.exec_())
