# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppression_etudiant_donne.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
import csv

class Ui_suppressionetudiantdonne(object):
    def setupUi(self, suppressionetudiantdonne):
        suppressionetudiantdonne.setObjectName("suppressionetudiantdonne")
        suppressionetudiantdonne.resize(1024, 870)
        suppressionetudiantdonne.setMaximumSize(QtCore.QSize(1024, 870))
        suppressionetudiantdonne.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(18, 178, 255, 254), stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(:/ressources/23.jpg);\n"
"background-color: rgb(54, 54, 54);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(suppressionetudiantdonne)
        self.label.setGeometry(QtCore.QRect(80, 340, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(suppressionetudiantdonne)
        self.lineEdit.setGeometry(QtCore.QRect(530, 350, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(suppressionetudiantdonne)
        self.pushButton.setGeometry(QtCore.QRect(380, 550, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(54, 54, 54);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(75, 75, 75);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.supprimer)
        self.label_2 = QtWidgets.QLabel(suppressionetudiantdonne)
        self.label_2.setGeometry(QtCore.QRect(240, 120, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(suppressionetudiantdonne)
        QtCore.QMetaObject.connectSlotsByName(suppressionetudiantdonne)
    def supprimer(self):
        numero_inscription=self.lineEdit.text()
        if not(numero_inscription.isdigit() and len(numero_inscription)==8):
            QMessageBox.critical(None, "error", "Veuillez entrer un numero d'inscription valide   (8 chiffres).")
            return
        with open('students.csv', 'r') as f:
            reader = csv.DictReader(f)
            students = list(reader)
        # Chercher les livres de l'année spécifiée
        etudiant_numero = [students for students in students if students['numero_inscription'] == numero_inscription]
        if not etudiant_numero:
            QMessageBox.information(None, "Aucun etudiant trouvé", f"Aucun etudiant avec ce numero d inscription {numero_inscription} a été trouvé.")
            return
        etudiant_restants = [students for students in students if students not in etudiant_numero]
        with open('students.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse' , 'mail' , 'telephone', 'section' , 'niveau_etude'])
            writer.writeheader()
            writer.writerows(etudiant_restants)
        QMessageBox.information(None, "etudiant supprimé", f"L'étudiant ayant le numéro d'inscription {numero_inscription} a été supprimés avec succès.")
             
    def retranslateUi(self, suppressionetudiantdonne):
        _translate = QtCore.QCoreApplication.translate
        suppressionetudiantdonne.setWindowTitle(_translate("suppressionetudiantdonne", "Form"))
        self.label.setText(_translate("suppressionetudiantdonne", "Entrer le Numéro d\'inscription"))
        self.pushButton.setText(_translate("suppressionetudiantdonne", "Supprimer"))
        self.label_2.setText(_translate("suppressionetudiantdonne", "Suppression étudiant donné"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppressionetudiantdonne = QtWidgets.QWidget()
    ui = Ui_suppressionetudiantdonne()
    ui.setupUi(suppressionetudiantdonne)
    suppressionetudiantdonne.show()
    sys.exit(app.exec_())
