# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppression_section_niveau_donnes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_suppression_section_niveau_donnes(object):
    def setupUi(self, suppression_section_niveau_donnes):
        suppression_section_niveau_donnes.setObjectName("suppression_section_niveau_donnes")
        suppression_section_niveau_donnes.resize(1024, 870)
        suppression_section_niveau_donnes.setMaximumSize(QtCore.QSize(1024, 870))
        suppression_section_niveau_donnes.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(18, 178, 255, 254), stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(:/ressources/23.jpg);\n"
"background-color: rgb(54, 54, 54);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(suppression_section_niveau_donnes)
        self.label.setGeometry(QtCore.QRect(160, 280, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(suppression_section_niveau_donnes)
        self.label_2.setGeometry(QtCore.QRect(160, 410, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.suppnivsect = QtWidgets.QPushButton(suppression_section_niveau_donnes)
        self.suppnivsect.setGeometry(QtCore.QRect(410, 600, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.suppnivsect.setFont(font)
        self.suppnivsect.setStyleSheet("color: rgb(54, 54, 54);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.suppnivsect.setObjectName("suppnivsect")
        self.suppnivsect.clicked.connect(self.supprimer)
        self.label_3 = QtWidgets.QLabel(suppression_section_niveau_donnes)
        self.label_3.setGeometry(QtCore.QRect(60, 80, 931, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(suppression_section_niveau_donnes)
        self.comboBox.setGeometry(QtCore.QRect(490, 280, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(suppression_section_niveau_donnes)
        self.comboBox_2.setGeometry(QtCore.QRect(490, 420, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.retranslateUi(suppression_section_niveau_donnes)
        QtCore.QMetaObject.connectSlotsByName(suppression_section_niveau_donnes)
    def supprimer(self):
        niveau=self.comboBox_2.currentText()
        section=self.comboBox.currentText()
        with open('students.csv', 'r') as f:
            reader = csv.DictReader(f)
            students = list(reader)
        etudiant_numero = [students for students in students if students['niveau_etude'] == niveau and students['section']==section]
        if not etudiant_numero:
            QMessageBox.information(None, "Aucun etudiant trouvé", f"Aucun etudiant trouvé pour la section {section} du niveau {niveau}.")
            return
        etudiant_restants = [students for students in students if students not in etudiant_numero]
        with open('students.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse' , 'mail' , 'telephone', 'section' , 'niveau_etude'])
            writer.writeheader()
            writer.writerows(etudiant_restants)
        QMessageBox.information(None, "etudiant supprimé", f"Les étudiants de la section{section} de niveau {niveau} ont été supprimés avec succès.")
             

        
    def retranslateUi(self, suppression_section_niveau_donnes):
        _translate = QtCore.QCoreApplication.translate
        suppression_section_niveau_donnes.setWindowTitle(_translate("suppression_section_niveau_donnes", "Form"))
        self.label.setText(_translate("suppression_section_niveau_donnes", "entrer la section"))
        self.label_2.setText(_translate("suppression_section_niveau_donnes", "entrer le niveau"))
        self.suppnivsect.setText(_translate("suppression_section_niveau_donnes", "supprimer"))
        self.label_3.setText(_translate("suppression_section_niveau_donnes", "Suppression des étudiants d\'une section et niveau"))
        self.comboBox.setItemText(0, _translate("suppression_section_niveau_donnes", "Cycle Préparatoire intégrée"))
        self.comboBox.setItemText(1, _translate("suppression_section_niveau_donnes", "License Info"))
        self.comboBox.setItemText(2, _translate("suppression_section_niveau_donnes", "License Tic"))
        self.comboBox.setItemText(3, _translate("suppression_section_niveau_donnes", "License électronique"))
        self.comboBox.setItemText(4, _translate("suppression_section_niveau_donnes", "Ingénieur électronique"))
        self.comboBox.setItemText(5, _translate("suppression_section_niveau_donnes", "Ingénieur Informatique"))
        self.comboBox_2.setItemText(0, _translate("suppression_section_niveau_donnes", "1 ére année"))
        self.comboBox_2.setItemText(1, _translate("suppression_section_niveau_donnes", "2 éme année"))
        self.comboBox_2.setItemText(2, _translate("suppression_section_niveau_donnes", "3 éme année"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppression_section_niveau_donnes = QtWidgets.QWidget()
    ui = Ui_suppression_section_niveau_donnes()
    ui.setupUi(suppression_section_niveau_donnes)
    suppression_section_niveau_donnes.show()
    sys.exit(app.exec_())
