# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppression_livre_annee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QApplication, QMessageBox
import csv

class Ui_suppression_livre_annee(object):
    def setupUi(self, suppression_livre_annee):
        suppression_livre_annee.setObjectName("suppression_livre_annee")
        suppression_livre_annee.resize(1024, 840)
        suppression_livre_annee.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"background-image: url(:/ressources/23.jpg);")
        self.label = QtWidgets.QLabel(suppression_livre_annee)
        self.label.setGeometry(QtCore.QRect(100, 320, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.psupplivreannee = QtWidgets.QPushButton(suppression_livre_annee)
        self.psupplivreannee.setGeometry(QtCore.QRect(390, 540, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.psupplivreannee.setFont(font)
        self.psupplivreannee.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.psupplivreannee.setObjectName("psupplivreannee")
        self.psupplivreannee.clicked.connect(self.supprimer_livre_annee)
        self.lineEdit = QtWidgets.QLineEdit(suppression_livre_annee)
        self.lineEdit.setGeometry(QtCore.QRect(560, 330, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(suppression_livre_annee)
        self.label_2.setGeometry(QtCore.QRect(270, 140, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(suppression_livre_annee)
        QtCore.QMetaObject.connectSlotsByName(suppression_livre_annee)
    def supprimer_livre_annee(self):
        annee = self.lineEdit.text()
        if not(annee.isdigit() and len(annee)==4 and int(annee)<=2023):
            QMessageBox.critical(None, "Année invalide", "Veuillez entrer une année d'édition valide   (4 chiffres et inférieure a 2023).")
            return
        with open('livres.csv', 'r') as f:
            reader = csv.DictReader(f)
            livres = list(reader)
        # Chercher les livres de l'année spécifiée
        livres_annee = [livre for livre in livres if livre['annee_edition'] == annee]
        if not livres_annee:
            QMessageBox.information(None, "Aucun livre trouvé", f"Aucun livre publié cette année {annee}-là n'a été trouvé.")
            return
         # Supprimer les livres trouvés
        livres_restants = [livre for livre in livres if livre not in livres_annee]
        with open('livres.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['reference', 'titre', 'nom_auteur', 'prenom_auteur', 'annee_edition'])
            writer.writeheader()
            writer.writerows(livres_restants)
        QMessageBox.information(None, "Livres supprimés", f"Les livres publiés en {annee} ont été supprimés avec succès.")
             



       
    def retranslateUi(self, suppression_livre_annee):
        _translate = QtCore.QCoreApplication.translate
        suppression_livre_annee.setWindowTitle(_translate("suppression_livre_annee", "Form"))
        self.label.setText(_translate("suppression_livre_annee", "donner l \'année d\'édition"))
        self.psupplivreannee.setText(_translate("suppression_livre_annee", "supprimer"))
        self.label_2.setText(_translate("suppression_livre_annee", "Suppression livre par année"))
import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppression_livre_annee = QtWidgets.QWidget()
    ui = Ui_suppression_livre_annee()
    ui.setupUi(suppression_livre_annee)
    suppression_livre_annee.show()
    sys.exit(app.exec_())
