# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppression_niveau_donne.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources


class Ui_suppression_niveau_donne(object):
    def setupUi(self, suppression_niveau_donne):
        suppression_niveau_donne.setObjectName("suppression_niveau_donne")
        suppression_niveau_donne.resize(1024, 870)
        suppression_niveau_donne.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-image: url(:/ressources/23.jpg);\n"
"background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(suppression_niveau_donne)
        self.label.setGeometry(QtCore.QRect(150, 330, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.suppniveau = QtWidgets.QPushButton(suppression_niveau_donne)
        self.suppniveau.setGeometry(QtCore.QRect(360, 540, 181, 41))
        self.suppniveau.setMaximumSize(QtCore.QSize(1024, 870))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.suppniveau.setFont(font)
        self.suppniveau.setStyleSheet("color: rgb(54, 54, 54);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.suppniveau.setObjectName("suppniveau")
        self.suppniveau.clicked.connect(self.supprimer)
        self.label_2 = QtWidgets.QLabel(suppression_niveau_donne)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 841, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(suppression_niveau_donne)
        self.comboBox.setGeometry(QtCore.QRect(510, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(3, "")

        self.retranslateUi(suppression_niveau_donne)
        QtCore.QMetaObject.connectSlotsByName(suppression_niveau_donne)
    def supprimer(self):
        niveau=self.comboBox.currentText()
        with open('students.csv', 'r') as f:
            reader = csv.DictReader(f)
            students = list(reader)
        etudiant_numero = [students for students in students if students['niveau_etude'] == niveau]
        if not etudiant_numero:
            QMessageBox.information(None, "Aucun etudiant trouvé", f"Aucun etudiant trouvé pour le niveau {niveau}.")
            return
        etudiant_restants = [students for students in students if students not in etudiant_numero]
        with open('students.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse' , 'mail' , 'telephone', 'section' , 'niveau_etude'])
            writer.writeheader()
            writer.writerows(etudiant_restants)
        QMessageBox.information(None, "etudiant supprimé", f"Les étudiants de  niveau {niveau} ont été supprimés avec succès.")
             
        

    def retranslateUi(self, suppression_niveau_donne):
        _translate = QtCore.QCoreApplication.translate
        suppression_niveau_donne.setWindowTitle(_translate("suppression_niveau_donne", "Form"))
        self.label.setText(_translate("suppression_niveau_donne", "Entrer le niveau"))
        self.suppniveau.setText(_translate("suppression_niveau_donne", "supprimer"))
        self.label_2.setText(_translate("suppression_niveau_donne", "Suppression les étudiants d\'un niveau d\'étude"))
        self.comboBox.setItemText(0, _translate("suppression_niveau_donne", "1 ére année"))
        self.comboBox.setItemText(1, _translate("suppression_niveau_donne", "2 éme année"))
        self.comboBox.setItemText(2, _translate("suppression_niveau_donne", "3 éme année"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppression_niveau_donne = QtWidgets.QWidget()
    ui = Ui_suppression_niveau_donne()
    ui.setupUi(suppression_niveau_donne)
    suppression_niveau_donne.show()
    sys.exit(app.exec_())
