# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppression_livre_donne.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources
from ajouter_livre import Ui_ajouter_livre
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_suppression_livre_donne(object):
    def setupUi(self, suppression_livre_donne):
        suppression_livre_donne.setObjectName("suppression_livre_donne")
        suppression_livre_donne.resize(1024, 840)
        suppression_livre_donne.setMaximumSize(QtCore.QSize(1024, 840))
        font = QtGui.QFont()
        font.setPointSize(12)
        suppression_livre_donne.setFont(font)
        suppression_livre_donne.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"background-image: url(:/ressources/23.jpg);")
        self.label = QtWidgets.QLabel(suppression_livre_donne)
        self.label.setGeometry(QtCore.QRect(100, 330, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.l1supplivre = QtWidgets.QLineEdit(suppression_livre_donne)
        self.l1supplivre.setGeometry(QtCore.QRect(570, 340, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1supplivre.setFont(font)
        self.l1supplivre.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.l1supplivre.setObjectName("l1supplivre")
        self.psupplivre = QtWidgets.QPushButton(suppression_livre_donne)
        self.psupplivre.setGeometry(QtCore.QRect(410, 510, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.psupplivre.setFont(font)
        self.psupplivre.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.psupplivre.setObjectName("psupplivre")
        self.psupplivre.clicked.connect(self.supprimer)
        self.label_2 = QtWidgets.QLabel(suppression_livre_donne)
        self.label_2.setGeometry(QtCore.QRect(190, 150, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(suppression_livre_donne)
        QtCore.QMetaObject.connectSlotsByName(suppression_livre_donne)
    def supprimer(self):
        
        reference=self.l1supplivre.text()
        with open('livres.csv', 'r') as f:
            reader = csv.DictReader(f)
            livres = list(reader)
        # Chercher les livres de l'année spécifiée
        livres_reference = [livre for livre in livres if livre['reference'] == reference]
        if not livres_reference:
            QMessageBox.information(None, "Aucun livre trouvé", f"le reference {reference} n existe pas dans notre base de données.")
            return
        livres_restants = [livre for livre in livres if livre not in livres_reference]
        with open('livres.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['reference', 'titre', 'nom_auteur', 'prenom_auteur', 'annee_edition'])
            writer.writeheader()
            writer.writerows(livres_restants)
        QMessageBox.information(None, "Livres supprimés", f"Le livre publié avec le reference: {reference} a été supprimés avec succès.")
          
            


    def retranslateUi(self, suppression_livre_donne):
        _translate = QtCore.QCoreApplication.translate
        suppression_livre_donne.setWindowTitle(_translate("suppression_livre_donne", "Form"))
        self.label.setText(_translate("suppression_livre_donne", "donner la référence de livre"))
        self.psupplivre.setText(_translate("suppression_livre_donne", "supprimer"))
        self.label_2.setText(_translate("suppression_livre_donne", "Suppression livre par référence"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppression_livre_donne = QtWidgets.QWidget()
    ui = Ui_suppression_livre_donne()
    ui.setupUi(suppression_livre_donne)
    suppression_livre_donne.show()
    sys.exit(app.exec_())
