# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suupression_section_donnee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
import csv
import ressources


class Ui_suppression_etudiant_section_donnee(object):
    def setupUi(self, suppression_etudiant_section_donnee):
        suppression_etudiant_section_donnee.setObjectName("suppression_etudiant_section_donnee")
        suppression_etudiant_section_donnee.resize(1024, 870)
        suppression_etudiant_section_donnee.setMaximumSize(QtCore.QSize(1024, 870))
        suppression_etudiant_section_donnee.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(18, 178, 255, 254), stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(:/ressources/23.jpg);\n"
"background-color: rgb(54, 54, 54);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(suppression_etudiant_section_donnee)
        self.label.setGeometry(QtCore.QRect(170, 350, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.suppsection = QtWidgets.QPushButton(suppression_etudiant_section_donnee)
        self.suppsection.setGeometry(QtCore.QRect(360, 550, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(16)
        self.suppsection.setFont(font)
        self.suppsection.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.suppsection.setObjectName("suppsection")
        self.suppsection.clicked.connect(self.supprimer)
        self.label_2 = QtWidgets.QLabel(suppression_etudiant_section_donnee)
        self.label_2.setGeometry(QtCore.QRect(160, 140, 731, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(suppression_etudiant_section_donnee)
        self.comboBox.setGeometry(QtCore.QRect(480, 360, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"border-radius:10px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(suppression_etudiant_section_donnee)
        QtCore.QMetaObject.connectSlotsByName(suppression_etudiant_section_donnee)
    def supprimer(self):
        section=self.comboBox.currentText()
        with open('students.csv', 'r') as f:
            reader = csv.DictReader(f)
            students = list(reader)
        etudiant_numero = [students for students in students if students['section'] == section]
        if not etudiant_numero:
            QMessageBox.information(None, "Aucun etudiant trouvé", f"Aucun etudiant trouvé pour la section {section} .")
            return
        etudiant_restants = [students for students in students if students not in etudiant_numero]
        with open('students.csv', 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['numero_inscription', 'nom', 'prenom', 'date_naissance', 'adresse' , 'mail' , 'telephone', 'section' , 'niveau_etude'])
            writer.writeheader()
            writer.writerows(etudiant_restants)
        QMessageBox.information(None, "etudiant supprimé", f"Les étudiants de  la section {section} ont été supprimés avec succès.")
             

    def retranslateUi(self, suppression_etudiant_section_donnee):
        _translate = QtCore.QCoreApplication.translate
        suppression_etudiant_section_donnee.setWindowTitle(_translate("suppression_etudiant_section_donnee", "Form"))
        self.label.setText(_translate("suppression_etudiant_section_donnee", "Entrer la section"))
        self.suppsection.setText(_translate("suppression_etudiant_section_donnee", "supprimer"))
        self.label_2.setText(_translate("suppression_etudiant_section_donnee", "Suppression les étudiants d\'une section"))
        self.comboBox.setItemText(0, _translate("suppression_etudiant_section_donnee", "Cycle Préparatoire intégrée"))
        self.comboBox.setItemText(1, _translate("suppression_etudiant_section_donnee", "License Info"))
        self.comboBox.setItemText(2, _translate("suppression_etudiant_section_donnee", "License Tic"))
        self.comboBox.setItemText(3, _translate("suppression_etudiant_section_donnee", "License électronique"))
        self.comboBox.setItemText(4, _translate("suppression_etudiant_section_donnee", "Ingénieur électronique"))
        self.comboBox.setItemText(5, _translate("suppression_etudiant_section_donnee", "Ingéniuer Informatique"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    suppression_etudiant_section_donnee = QtWidgets.QWidget()
    ui = Ui_suppression_etudiant_section_donnee()
    ui.setupUi(suppression_etudiant_section_donnee)
    suppression_etudiant_section_donnee.show()
    sys.exit(app.exec_())
